### ISSUE TITLE
Additional flag to blockchainScripthash_subscribe 

### ISSUE THREAD

**Issue by gbenattar** [romanz/electrs#177]
Hi,
In our wallet we call blockchainScripthash_subscribe for newly derived addresses and after performing an investigation in Electrs we found out that it is consuming for Electrs to retrieve the status (Electrum hash) and "confirmed". 

For those addresses we know that `status` is empty so our proposal is to change the API and add an extra flag (default true for backward compatibility) to not perform the scan and directly return.

What do you think? @romanz

**Comment by oleiba** [comment]
I would like to add that this scan-and-filter-by-address method is used not only upon _subscription_, but also periodically upon [`update_subscriptions`](https://github.com/romanz/electrs/blob/9df66d97e3d3c3f12ad73d485b768bbaabba3f91/src/rpc.rs#L335).
This is done for every single subscribed address separately.
I would suggest to refactor it so the process would go over the history (confirmed and mempool) in _one_ pass, and then filter transactions by _any_ of the subscribed addresses. 

This can also be further optimized, since there's no need to go over blocks prior to the highest block which is common (i.e. same hash) between the _current_ periodic update and the _previous_, but I would say the previous fix alone should already eliminate much of the load.

**Comment by oleiba** [comment]
Related: https://github.com/romanz/electrs/issues/146

**Comment by romanz** [comment]
> For those addresses we know that `status` is empty so our proposal is to change the API andadd an extra flag (default true for backward compatibility) to not perform the scan and directly return.

It can be done, but wouldn't it be easier to do it client-side (i.e. skip querying these addresses)?

**Comment by oleiba** [comment]
@romanz I don't see how you can do it client-side, you want to subscribe an address at a point in time where it was created therefore known for having no history, but to get notifications whenever a new relevant tx appears.

**Comment by romanz** [comment]
Oops, I misunderstood the issue...
The suggestion sounds good to me, please open a PR :)
