### ISSUE TITLE
Unnecessary access of electrs homedir, prevents systemd hardening

### ISSUE THREAD

**Issue by Stadicus** [romanz/electrs#217]
When running Electrs as a systemd unit, I usually harden the configuration by including the following access limitation:

```sh
# Deny access to /home, /root and /run/user
ProtectHome=true
```

In my specific configuration, the user `electrs` does not need to have a home directory, as the configuration file is located at `/etc/electrs/electrs.conf` and the `db-dir` is on a different drive. But if I include the restriction above, Electrs fails to start with the following error message:

```sh
Error: Failed to read configuration file /home/electrs/.electrs/config.toml: Permission denied (os error 13)
```

This seems to indicate that Electrs tries to access its service user's home directory nonetheless, and fails because it's not accessible. I think it would be good practice to not access this directory if not necessary.

Here's the full systemd unit file for reference:

```systemd
[Unit]
Description=Electrs server daemon
After=bitcoind.service

[Service]

# Service execution
###################

ExecStart=/usr/bin/electrs --conf /etc/electrs/electrs.conf

# Process management
####################

Type=simple
Restart=always
TimeoutSec=120
RestartSec=30
KillMode=process


# Directory creation and permissions
####################################

# Run as electrs:bitcoin
User=electrs
Group=bitcoin

# /run/electrs
RuntimeDirectory=electrs
RuntimeDirectoryMode=0710

# Hardening measures
####################

# Provide a private /tmp and /var/tmp.
PrivateTmp=true

# Mount /usr, /boot/ and /etc read-only for the process.
ProtectSystem=full

# Deny access to /home, /root and /run/user
ProtectHome=true

# Disallow the process and all of its children to gain
# new privileges through execve().
NoNewPrivileges=true

# Use a new /dev namespace only populated with API pseudo devices
# such as /dev/null, /dev/zero and /dev/random.
PrivateDevices=true

# Deny the creation of writable and executable memory mappings.
MemoryDenyWriteExecute=true

[Install]
WantedBy=multi-user.target
```

**Comment by romanz** [comment]
Good catch, thanks!
Will fix it soon.

**Comment by romanz** [comment]
CC: @Kixunil 
Maybe we should handle this case in `configure_me` (in addition to `NotFound`)?
https://github.com/Kixunil/configure_me/blob/924e19a23d1b1eea664034027ffb82de8519a3b4/configure_me_codegen/src/codegen.rs#L855

**Comment by Kixunil** [comment]
Hmm, this is something I ran into as well but decided to solve by making the relevant directory home. There's a good reason for that check to be there - it's to avoid silently skipping unreadable files and then pulling hair. (That's like one of the worst kinds of bugs there can be...)

I personally believe that setting home to wherever your database is stored is the cleanest way to approach this problem at least short term (and I think that it's also good long term). I'm very open to adding some sensible way of skipping config files, I just don't want to silently ignore them the way PR suggests.

I'm thinking of adding a feature to `configure_me` that'd enable skipping default config files by specifying `--no-default-configs` (or any other name you want). What do you think?

**Comment by Kixunil** [comment]
So I created https://github.com/Kixunil/configure_me/issues/37 with in-depth design proposal. If you have a better idea, I want to know!

**Comment by Kixunil** [comment]
FYI I set home to the database directory in [debcrafter](https://github.com/Kixunil/debcrafter/blob/d62d090ed7f8e14370fa0f5b1f146b897a3cd598/src/postinst.rs#L247), which I use in [cryptoanarchy-deb-repo-builder](https://github.com/Kixunil/cryptoanarchy-deb-repo-builder/blob/master/pkg_specs/electrs-mainnet.sps#L6) and it works very well.

I'd still like to skip defaults to avoid footgun, in case someone places `electrs` into `/etc`, since I divide instances of mainnet and testnet...

**Comment by Stadicus** [comment]
> So I created [Kixunil/configure_me#37](https://github.com/Kixunil/configure_me/issues/37) with in-depth design proposal. If you have a better idea, I want to know!

That would certainly solve my issue.

I'm not familiar with the `configure_me` library and it's applications outside of Electrs. One thing I don't quite understand: if I explicitly provide a config file (using the `--config` option), why should other locations still be checked? If my config file is not accessible, I'd like the program probably to exit, and not start with a different configuration that might cause damage.

So in my case, I would not really need the separate option. If I provide a specific config flag, all other locations could savely be ignored.

**Comment by Kixunil** [comment]
Good points. One of the goals of `configure_me` is to make applications written using it conform to all reasonable behaviors that can be seen in other Linux CLI applications. That's why it e.g. supports both `--foo=bar` and `--foo bar` style arguments, man pages and lot of other stuff. One of the properties that we can observe in some applications is having multiple-level configuration, where there can be system-default configuration (usually in `/etc`), user-level configuration (in `$HOME/.app_name`) and finally whatever custom config files a user has. All this can be overridden by env vars and args.

Now, it's a good question what should be done if config file is specified explicitly. Most software I've seen adds (merges) configuration files (overriding previous options) over completely replacing them. Examples: `gpg`, `gcc`. They provide separate option to turn off the defaults entirely. I'm not saying this is the best possible approach and I'd eagerly remove such behavior if there seemed to be too many problems with it ("reasonable" mentioned above). Right now I don't see it as a huge problem and quite possibly keeping it consistent with other stuff is even safer as that's what most people familiar with Linux/Unix would expect.

Of course, being unable to turn defaults off is very bad, I'm going to give it "bug" label and resolve ASAP.

**Comment by romanz** [comment]
> I'm thinking of adding a feature to `configure_me` that'd enable skipping default config files by specifying `--no-default-configs` (or any other name you want). What do you think?

Sounds great, will close https://github.com/Kixunil/configure_me/pull/36 - as https://github.com/Kixunil/configure_me/pull/37 is indeed much better.

**Comment by xanoni** [comment]
Running into the same issue. I have these lines in my `electrs.service` systemd script, but `electrs` still wants to read from `/home/electrs/.electrs/config.toml`, which should not be necessary if I'm explicitly defining the location of the config. Can someone explain the logic here?

```
[...]
  14 ExecStart=/usr/local/bin/electrs --conf=/mnt/ssd/electrs-data/electrs.conf
[...]
  54 ProtectHome=true
[...]
```

Log:

```
systemd[1]: Started Electrs daemon.
electrs[24192]: Error: Failed to read configuration file /home/electrs/.electrs/config.toml: Permission denied (os error 13)
systemd[1]: electrs.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: electrs.service: Failed with result 'exit-code'.
systemd[1]: electrs.service: Service RestartSec=30s expired, scheduling restart.
systemd[1]: electrs.service: Scheduled restart job, restart counter is at 11.
systemd[1]: Stopped Electrs daemon.
```

**Comment by xanoni** [comment]
By the way, the workaround I'm using for now is `ProtectHome=tmpfs` ... creates an empty dummy home folder:

```
If set to "tmpfs", temporary file systems are mounted on the three directories in read-only mode. The value "tmpfs" is useful to hide home directories not relevant to the processes invoked by the unit, while still allowing necessary directories to be made visible when listed in BindPaths= or BindReadOnlyPaths=.
```

See: https://www.freedesktop.org/software/systemd/man/systemd.exec.html

**Comment by sunknudsen** [comment]
Hey guys, any process on this issue?

I really appreciate hardening potential discussed here.

I am likely missing something, but `--features "ignore_default_config_files"` doesn’t work on v0.9.5.

**Comment by sunknudsen** [comment]
Really appreciate hardening effort discussed here… is `--features "ignore_default_config_files"` expected to work on v0.9.5?

**Comment by Kixunil** [comment]
@sunknudsen it should work however note the recent PR to do this properly.
