### ISSUE TITLE
Is using only 8 bytes of txid "safe"? 

### ISSUE THREAD

**Issue by dpc** [romanz/electrs#251]
Looking at https://github.com/romanz/electrs/blob/master/doc/schema.md, I've noticed that `electrs` is using only 8 bytes of txids for keys. I do the same optimization in `rust-bitcoin-indexer`, but I've used 16 bytes ... because I was afraid of birthday attacks.

Since calculating txids is not computationally difficult, I could imagine an attacker grinding for two valid txes with the same prefix, and it seems totally doable to me. Am I missing something here that would prevent it?

Is `electrs` just resistant to such a collision causing problems?

**Comment by Kixunil** [comment]
I was wondering about this too but never had the time to look. So far a few general notes:

The attack scenarios I can imagine:

* DoS of `electrs` - we need to check that duplicates won't cause it to panic etc
* Double spend attacks - protected by `bitcoind`, but can an attacker optimize the attack somehow? So far I think it's not possible because every output going to the address of the merchant must really be present to be included.
* Can an attacker cause the merchant transaction to "vanish" from `electrs`? That means replacing a transaction in `electrs` database with another one, causing the merchant to stop seeing it in Electrum despite it being confirmed.

**Comment by romanz** [comment]
In case of a collision, there would be more than 1 transaction matching a given scripthash.
Since electrs assumes there is a trusted full node, it will retrieve all the transactions - and will return only the ones that have an output that matches the full scripthash.
By allowing some collisions - and by handling them via verification of the actual transactions from a full node, I think the code should be correct and save some storage space :)

**Comment by Kixunil** [comment]
How realistic would it be to generate many such IDs in order to consume lot of resources? My intuition says not very easy, but I'm not in the state of being able to think about it clearly, so I may be missing something.

**Comment by romanz** [comment]
Good point - will also need to think about it.

**Comment by dpc** [comment]
I might be wrong but my understanding is that 8B gives you only 4B of security against birthday-attacks. Which is just 4billion . So a home desktop computer should be able to grind at least some txes that that have the same prefix. But AFAIU the collisions would be random, so I don't think the attacker can "pile them up". So it's a lot of effort, just to make the electrs fetch 2 maybe 3 txes, instead of just 1 sometimes. Probably not worthwhile the trouble.

For `rust-bitcoin-indexer` the consequences would be much more dire as these are used in as keys in the db, for joins etc. and even if I can detect a collision, there's nothing graceful to do in that case., so I guess I regrettably have to keep 16B keys.

**Comment by Kixunil** [comment]
I was thinking along the same lines. Wasn't sure if there is some edge case, but I don't see any.

Is this issue resolved then?

**Comment by dpc** [comment]
I think so. I was hoping that someone tells me that I'm wrong and I could cut 16B into 8B. But it looks that electrs is just resistant through other means.
