### ISSUE TITLE
set daemon_dir

### ISSUE THREAD

**Issue by inzider** [romanz/electrs#264]
Hi!

I have set the daemon_dir to a /media/ dir in the config but still the electrum server always look at /home/user/./bitcoin for the block dir.

    "INFO - listing block files at /home/user/./bitcoin/block/blk*.dat"

Then this error occur: 
    thread 'bulk_writer' panicked at 'no indexed header found', src/bulk.rs:66:27

Here is the config setting : 
    [[param]]
    name = "daemon_dir"
    type = "std::path::PathBuf"
    doc = "Data directory of Bitcoind (default: /media/user/BLOCK/Files/.bitcoin)"
    default = "crate::config::default_daemon_dir()" 

I also tried to start the server with --daemon-dir=/media/user/BLOCK/Files/.bitcoin
but the server always look at /home/user/./bitcoin dir. 

Any help would be appreciated.

**Comment by romanz** [comment]
Thanks for reporting this issue!
Could you please attach the verbose log from running:
```
cargo run --release -- --daemon-dir /media/user/BLOCK/Files/.bitcoin/ -vvvv
```

**Comment by Kixunil** [comment]
@inzider what do you mean by "Here is the config setting"? Are you trying to use `config_spec.toml` file as your config file? Because that's not a configuration file. Please read [the guide](https://github.com/romanz/electrs/blob/master/doc/usage.md#electrs-configuration) to learn how to configure `electrs`.

However, `--daemon-dir=...` should work fine.

**Comment by inzider** [comment]
@romanz @Kixunil Thanks for the suggestion. You are right --daemon-dir in terminal did work. And yes I was using config_spec.toml as config, I will look closely at the guide.
