### ISSUE TITLE
Server does not want to shut down when I press Ctrl + C

### ISSUE THREAD

**Issue by jonjonez** [romanz/electrs#283]
When I press Ctrl + C to stop the server, it seems to crash, this was not the first time, the last time I closed the terminal abruptly and when I started Electrs again he no longer connected to Electrum or another wallet that supports servers.

I had to delete the DB folder where the indexed files are in order to download everything again which took ~ 5 hours for the server to reconnect the wallets again, what should I do when that happens?

**Comment by jonjonez** [comment]
[https://imgur.com/lKF8g6p](url)

**Comment by jonjonez** [comment]
As he is not terminating the process by Ctrl + C, the only alternative I have left would be to close the terminal, but doing so will corrupt the entire database and I will have to do everything again...

**Comment by Kixunil** [comment]
The issue is pretty obvious:

In the logs we can see `RPC Done`, this is [logged](https://github.com/romanz/electrs/blob/3f750cf8ceef2826ac1a59e8488f3f4a952ec70d/src/rpc.rs#L397) in `handle_replies`, which is responsible for [receiving](https://github.com/romanz/electrs/blob/3f750cf8ceef2826ac1a59e8488f3f4a952ec70d/src/rpc.rs#L396) messages.
Upon encountering `Message::Done` it [returns](https://github.com/romanz/electrs/blob/3f750cf8ceef2826ac1a59e8488f3f4a952ec70d/src/rpc.rs#L421) leaving the channel open with nothing to handle the messages. The channel fills up and then the [code responsible for cleanup](https://github.com/romanz/electrs/blob/3f750cf8ceef2826ac1a59e8488f3f4a952ec70d/src/rpc.rs#L600) gets stuck.

Solution: close the channel before returning. I'm going to try to make a PR.

**Comment by Kixunil** [comment]
@jonjonez I'm surprised that it'd corrupt the database, I see no reason for it. Maybe there's something else that looked like corrupted database?

**Comment by Kixunil** [comment]
@jonjonez Could you try using my branch from the PR?

**Comment by jonjonez** [comment]
When I say corrupted db, I mean this:

![image](https://user-images.githubusercontent.com/23480437/88813978-ed4d0e00-d18f-11ea-85b9-da5653ce0445.png)

When this happens, the server does not connect to any wallet, it’s like it’s corrupted, I don’t know how to solve it, unless I delete everything in the db folder and do it again as I’ve done previously, but now it happened again

**Comment by Kixunil** [comment]
Oh, it shouldn't be corrupted *db*, could be corrupted memory. (So resyncing is pointless.) There was a report about inconsistent mempool which I suspected was not an `electrs` bug, but maybe it it. I can't look at it properly right now.

Are you sure you do **not** have pruning enabled on bitcoind?

**Comment by jonjonez** [comment]
Yes, I' did not activate any pruning.

Thank you

**Comment by romanz** [comment]
> When I say corrupted db, I mean this:
> 
> ![image](https://user-images.githubusercontent.com/23480437/88813978-ed4d0e00-d18f-11ea-85b9-da5653ce0445.png)

The error above happens when syncing the mempool with bitcoind - see `Tracker::update()`:
```rust
    pub fn update(&mut self, daemon: &Daemon) -> Result<()> {
        let new_txids = daemon
            .getmempooltxids()
            .chain_err(|| "failed to update mempool from daemon")?;
        let old_txids = HashSet::from_iter(self.items.keys().cloned());

        let txids_iter = new_txids.difference(&old_txids);
        let entries: Vec<(&Txid, MempoolEntry)> = txids_iter
            .filter_map(|txid| {
                match daemon.getmempoolentry(txid) {
                    Ok(entry) => Some((txid, entry)),
                    Err(err) => {
                        warn!("no mempool entry {}: {}", txid, err); // e.g. new block or RBF
                        None // ignore this transaction for now
                    }
                }
            })
            .collect();
    ...
```
We first use `getmempooltxids` RPC to get all current mempool transaction IDs, and then download only the new entries using `getmempoolentry` RPC. There is an inherent race - due to concurrent block confirmation / RBF - so we issue the warning above.

OTOH, it should not prevent normal operation of the server...

**Comment by Kixunil** [comment]
> There is an inherent race - due to concurrent block confirmation / RBF

Would it be worth modifying the code to try to detect those situations so that there aren't those (scary?) warnings?
