### ISSUE TITLE
Please document the blk import mechanism

### ISSUE THREAD

**Issue by schildbach** [romanz/electrs#324]
I could not find any documentation about that mechanism, except how to disable it via `ELECTRS_JSONRPC_IMPORT=true`.

Questions I could not answer:

- After importing is done, are the bitcoind blk files still needed? Or will sync continue via RPC?
- If `blocks_dir` is configured, is `daemon_dir` still needed? If so, why?
- Pointing something to `/home/user/.bitcoin` seems like a no-go to me, since that directory could potentially contain a wallet.

No need to answer these questions here. Just a documentation section about the import mechanism would be useful.

**Comment by Kixunil** [comment]
`daemon_dir` should not be needed.

Yes, pointing `electrs` to daemon dir is problemetic. Unfortunately it's not easy to isolate them by running under a different user since all files created by bitcoind use paranoid umask and if you disable this umask using `sysperms=1` you also disable the wallet. This sucks as it could conflict with something else requiring the wallet. I solved it in my project by just using `jsonrpc_import = true` so far nobody complained about the speed.

**Comment by sentree** [comment]
I see this has already been added to the next milestone, but I think my anecdote may be useful in the documentation effort. Like @schildbach, I also didn't feel comfortable giving `electrs` access to my `/home/user/.bitcoin/` directory. After reading through `docs/usage.md`, I ran a test on a different machine to see how I could restrict this access.

The setup on my test machine ran `bitcoind` under a `bitcoin` user and `electrs` under an `electrum` user, with a cookie shared in a `tmpfs` they both had access to (read-write for `bitcoin, read-only for `electrum`). I initially attempted to give `electrs` read-only access to just the `/home/bitcoin/.bitcoin/blocks/` directory by using [bindfs](https://bindfs.org) to mount it to `/home/electrum/.bitcoin/blocks/` directory. This should theoretically solve the permissions issue that @Kixunil brings up above. The initial sync seemed to be working, but failed when it reached the end of the chain:

```
2020-12-07T11:30:41.444-05:00 - TRACE - indexed "/home/electrum/.bitcoin/blocks/blk02349.dat": 1501487 rows
2020-12-07T11:30:53.494-05:00 - TRACE - indexed "/home/electrum/.bitcoin/blocks/blk02350.dat": 1387351 rows
2020-12-07T11:31:05.145-05:00 - TRACE - indexed "/home/electrum/.bitcoin/blocks/blk02351.dat": 1272683 rows
2020-12-07T11:31:07.261-05:00 - DEBUG - no more blocks to index
2020-12-07T11:31:07.261-05:00 - TRACE - indexed "/home/electrum/.bitcoin/blocks/blk02352.dat": 252112 rows
thread 'bulk_writer' panicked at 'indexing failed: Error(Msg("failed to index \"/home/electrum/.bitcoin/blocks/blk01557.dat\""), State { next_error: Some(Error(Msg("failed to parse block at 103282696..104056970"), State { next_error: Some(UnsupportedSegwitFlag(0)), backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
2020-12-07T11:31:08.037-05:00 - TRACE - closing DB at "/home/electrum/.electrs/db/mainnet"
thread 'main' panicked at 'writer panicked: Any', src/libcore/result.rs:1188:5
```

I repeated the experiment to see if the error was due to a transient issue, but it occurred in both of my subsequent attempts. I ended up doing some research at this point and thankfully found this issue. Setting `jsonrpc_import = true` solved the issue and the initial sync was fast enough for me, so I'll stick with it. I definitely think this option should be mentioned in `docs/usage.md` since multiple people seem to want to limit access to `/home/user/.bitcoin/` directory.

For users that want to limit access and have a fast initial sync, it might be worth investigating why the sync fails if the blocks database files are read-only. The sync seemed to be making good progress with until it reached the very end of the chain.

**Comment by Kixunil** [comment]
@sentree nice research, I was also thinking about `bindfs` but I believe making Bitcoin Core not be overly paranoid is a saner approach. I'm still very surprised `bindfs` causes crash at the end. Might be worth investigating as it could also uncover other problems.

All options are documented in `--help` or manpage, however, you have a point that `jsonrpc_import` is quite important so would make sense to give it a bit more visibility.

Note that restricting access like this doesn't help you if you directly share the cookie. If `electrs` got compromise, it could do bad things over RPC equivalent to obtaining write access:

* spend from wallet
* call `invalidateblock`
* probably bunch of others, those above are the most obvious dangers

To solve this issue, I highly recommend using either the new RPC whitelisting feature of bitcoind (latest version only) or [`btc-rpc-proxy`](https://github.com/Kixunil/btc-rpc-proxy). You can also take a look at [my project](https://deb.ln-ask.me) which uses this kind of secure configuration out-of-the-box.

**Comment by schildbach** [comment]
Just out of the blue. Maybe it's an issue of concurrent access near the end of blocks: electrs tries to read the last blocks while Bitcoin Core has the same file locked for appending blocks. Or something similar to that.

**Comment by Kixunil** [comment]
Hmm, I think that reading the last block file could be quite a footgun in general. @romanz what do you think about intentionally excluding the last file from direct reading? That means read all the remaining blocks using RPC.

**Comment by romanz** [comment]
FTR, `blk*.dat` reading will be deprecated in favor of p2p-based sync in the upcoming electrs release (0.9.x)
