### ISSUE TITLE
Bug: Failed to syncronize from ARM64 - allocation of oversized vector

### ISSUE THREAD

**Issue by waltercool** [romanz/electrs#351]
**Describe the bug**
Trying to synchronize from SoC 8GB RAM, it crash.

panicked at 'failed sending blocks to be indexed: "SendError(..)"', index.rs:390:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Caused by: allocation of oversized vector: requested 5368216, maximum 4000000

**To Reproduce**
1. Compile v0.8.6 on ARM64, doesn't matter if system rocksdb or static one.
2. Sync with index_batch_size = 20 and jsonrpc_import = true
3. Wait

**Expected behavior**
Should work

**Configuration**

<details>
<summary>electrs.toml</summary>

```
index_batch_size = 20
jsonrpc_import = true
cookie_file = "/var/lib/bitcoincash-node/.cookie"
daemon_dir = "/var/lib/bitcoincash-node/"
db_dir = "/var/lib/bitcoincash-node/db"
network = "bitcoin"
electrum_rpc_addr = "127.0.0.1:50001"
verbosity = 3
```
</details>
<details>

<summary>Error</summary>

```
panicked at 'failed sending blocks to be indexed: "SendError(..)"', index.rs:390:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Caused by: allocation of oversized vector: requested 5368216, maximum 4000000
```
</details>

Environment variables: `ELECTRS_X=Y;...`
Arguments: `--foo`

**System running electrs**
 - Deployment method: Manually compiled, from last tag.
 - OS name and version: Arch Linux ARM64

**Electrum client**
Client name (if not upstream desktop Electrum) and version: Haven't tried.

**Additional context**
.

**Comment by Kixunil** [comment]
This is clearly caused by you not using Bitcoin. Your chain is incompatible as it's too big. The check is performed by `rust-bitcoin` crate. You probably should ask **them** to remove it.

I personally don't find my time worth spending on solving problems of non-Bitcoin coins. So I'm leaving this discussion. Checking if this is a general problem seemed useful, it's not. The code is here if anyone wants to dig: https://docs.rs/bitcoin/0.17.1/src/bitcoin/consensus/encode.rs.html

@romanz IDK if you have/want to have an official policy on stuff like this. Perhaps worth documenting if yes. I respect your choice either way. (If you want to discuss it with me, please reach out in another way, I'm unsubscribing from this issue. I guess you don't have to ask me, your project, your choice.)

**Comment by waltercool** [comment]
I'm syncing Bitcoin cash. Isn't this considered as a same?

**Comment by romanz** [comment]
I suggest trying https://github.com/BitcoinUnlimited/ElectrsCash

**Comment by romanz** [comment]
> IDK if you have/want to have an official policy on stuff like this. 

I think that https://github.com/rust-bitcoin/rust-bitcoin#policy-on-altcoinsaltchains is reasonable.
