### ISSUE TITLE
Feature: ElectrumX RPC/CLI or equivalent for 'getinfo' and 'stop'

### ISSUE THREAD

**Issue by eugenesan** [romanz/electrs#852]
I am considering replacing ElectrumX with Electrs.

ElectrumX offers CLI/RPC functions ('[stop](https://electrumx.readthedocs.io/en/latest/rpc-interface.html#stop), '[getinfo](https://electrumx.readthedocs.io/en/latest/rpc-interface.html#getinfo)') which are necessary when running the node periodically on a non-stationary device.

I could not find how to safely terminate the service or fetch it's current status (block height).

**Comment by eugenesan** [comment]
For now, as a workaround, I've hacked the following:
`
estop() {
	# Fetch Electrs PID
	EPID=$(netstat -lnpt 2> /dev/null | grep 50001 | cut -d'/' -f1 | awk '{print $7}')

	# Stop Electrs
	kill -n 15 ${EPID}
}

elblock() {
	EBLOCK=$(echo '{"jsonrpc": "2.0", "method": "blockchain.headers.subscribe", "params": ["", "1.4"], "id": 0}' | nc -N 127.0.0.1 8335 | cut -d"{" -f3 | cut -d"," -f1 | cut -d":" -f2)
	echo "Block# ${EBLOCK}"
}
`
I hope some will come up with a better way.

**Comment by Kixunil** [comment]
Electrs receives and processes signals properly so yes, sending a signal is correct and safe way to terminate it.
Your script also looks correct, although I'd suggest using `jq` to process the output instead of hacky parsing.

I highly recommend that you use systemd service file for management. You avoid problems with things like PID being invalid and it provides you nice interface to start, stop, includin automatically stopping at shutdown and optionally starting on boot. We have an example service file in the doc.

**Comment by romanz** [comment]
BTW, electrs can export [Prometheus metrics in text format](https://prometheus.io/docs/instrumenting/exposition_formats/), so you can also use:
```
$ curl -s localhost:4224 | grep 'index_height{type="tip"}' | cut -d' ' -f2
```
