### ISSUE TITLE
Feature: consider using `bitcoin_slices` for parsing

### ISSUE THREAD

**Issue by romanz** [romanz/electrs#864]
**Is your feature request related to a problem? Please describe.**
It should improve block parsing performance (by doing less memory allocations).

**Describe the solution you'd like**
We can parse [Bitcoin blocks received via p2p](https://github.com/romanz/electrs/blob/3fa3e644ce20dc56b57168c755c0f73f0f94e228/src/p2p.rs#L352) using https://github.com/RCasatta/bitcoin_slices.

**Comment by shaurya947** [comment]
Hi @romanz could you please provide some high-level guidance on how you see this enhancement being implemented?

I understand the performance benefits of using `bsl::Block` for deserializing over `bitcoin::Block`, but since `RawNetworkMessage::parse()` returns `Result<NetworkMessage>`, how do we go about using `bsl::Block` in the context of `NetworkMessage`? Would we consider some new wrapper return type that could handle both `NetworkMessage` and `bsl::Block`, and update the downstream usages inside `p2p_loop`?

**Comment by romanz** [comment]
@shaurya947 Please see #913 (sorry for not linking it here earlier)

**Comment by shaurya947** [comment]
> @shaurya947 Please see #913 (sorry for not linking it here earlier)

ACK :smile: I guess I should have also checked PRs first. Either way it was a good mental exercise for me. I shall find some other issues to contribute. Please let me know if you have any in mind!

**Comment by romanz** [comment]
No problem, and thanks for the help!
I'd suggest https://github.com/romanz/electrs/labels/good%20first%20issue :)
