### ISSUE TITLE
Duplicate headers download with --jsonrpc-import

### ISSUE THREAD

**Issue by stevenroose** [romanz/electrs#99]
So I'm using `--jsonrpc-import`. The first run, block headers are downloaded. However, I had to close the program and restart. The second run it seems like all the headers of undownloaded blocks are downloaded again. 

Somehow this is taking a superlong time here, seemingly a lot longer than initial header download (perhaps individual HTTP connections + VPN + node @ different location; perhaps logging to encrypted fs (I added trace logs for all calls); perhaps because of the checking it's also reading the header to compare it instead of just writing all). I'm doing about 30 per second, which is several hours to get just the headers.

Why is this second check needed (apart from perhaps last several blocks)?

**Comment by romanz** [comment]
Thanks for reporting this issue!

IIUC, it happens because the 2nd time the block headers' download starts from the tip, and goes backward, one block header at a time:
https://github.com/romanz/electrs/blob/3982c9fd7872767331a745599131ac10f107c784/src/daemon.rs#L595-L626

If the initial indexing (that uses the more efficient `get_all_headers()`) doesn't finish successfully, the following block header downloads will be indeed much less efficient :/

**Comment by romanz** [comment]
I think that the solution may be refactoring `get_all_headers()` so it could start from a somewhat recent block (instead from genesis) to make block headers' download much more efficient in the case above.

**Comment by romanz** [comment]
Latest release should store indexed headers in the DB, and use p2p for syncing only the new headers.

**Comment by romanz** [comment]
Latest release should use p2p for block syncing - so hopefully it should be more efficient.
Please reopen if the issue persists.
